import type { Annotation, Author, Comment } from "./types";

export const authors: Record<string, Author> = {
  mina: {
    id: "mina-okafor",
    name: "Mina Okafor",
    handle: "@mina.notes",
    initials: "MO",
    accent: "#B54732",
    bio: "Urban systems researcher. I annotate the details that change the whole argument.",
  },
  teo: {
    id: "teo-baptista",
    name: "Teo Baptista",
    handle: "@teob",
    initials: "TB",
    accent: "#627663",
    bio: "Documentary editor collecting useful fragments from long conversations.",
  },
  amelie: {
    id: "amelie-roux",
    name: "Amélie Roux",
    handle: "@amelieroux",
    initials: "AR",
    accent: "#58728D",
    bio: "Product designer studying tools for thought and public memory.",
  },
  eduardo: {
    id: "eduardo-lopez",
    name: "Eduardo López",
    handle: "@loama",
    initials: "EL",
    accent: "#B54732",
    bio: "Builder and researcher turning useful moments into durable context.",
  },
};

export const seedAnnotations: Annotation[] = [
  {
    id: "the-value-of-good-questions",
    sourceType: "video",
    sourceUrl: "https://www.youtube.com/watch?v=UF8uR6Z6KLc",
    sourceDomain: "youtube.com",
    sourceTitle: "Steve Jobs' 2005 Stanford Commencement Address",
    sourcePublisher: "Stanford",
    sourceImage: "https://i.ytimg.com/vi/UF8uR6Z6KLc/hqdefault.jpg",
    mediaUrl: "/api/media?path=media%2Fseed%2Fstanford-commencement-482-553.mp4",
    mediaContentType: "video/mp4",
    startSeconds: 482,
    endSeconds: 553,
    resolution: 240,
    commentary: "The important distinction here is not between certainty and doubt. It is between a life arranged to avoid regret and one arranged to keep curiosity alive. The second creates better questions, and better questions compound.",
    createdAt: "2026-07-31T17:42:00.000Z",
    author: authors.mina,
    applause: 184,
    commentCount: 23,
    tags: ["decision making", "curiosity"],
  },
  {
    id: "cities-remember-through-rivers",
    sourceType: "article",
    sourceUrl: "https://www.nasa.gov/earth/earth-observatory/a-river-runs-through-it/",
    sourceDomain: "nasa.gov",
    sourceTitle: "A river runs through it",
    sourcePublisher: "NASA Earth Observatory",
    sourceImage: "https://images-assets.nasa.gov/image/iss067e357804/iss067e357804~large.jpg",
    excerpt: "Rivers are among the most powerful forces shaping the surface of our planet, and the marks they leave are visible from orbit.",
    commentary: "Maps teach us to see rivers as lines. From orbit they look more like sentences, continuously revised by weather, geology, and the decisions of everyone upstream.",
    createdAt: "2026-07-31T10:18:00.000Z",
    author: authors.amelie,
    applause: 127,
    commentCount: 14,
    tags: ["cities", "climate"],
  },
  {
    id: "silence-is-part-of-the-answer",
    sourceType: "podcast",
    sourceUrl: "https://www.npr.org/podcasts/510289/planet-money",
    sourceDomain: "npr.org",
    sourceTitle: "Planet Money",
    sourcePublisher: "NPR",
    mediaUrl: "/api/media?path=media%2Fseed%2Fplanet-money-1084-1168.mp3",
    mediaContentType: "audio/mpeg",
    startSeconds: 1084,
    endSeconds: 1168,
    commentary: "Listen to the pause before the answer. That silence contains the real cost of the decision. Audio preserves hesitation in a way a transcript almost always edits away.",
    createdAt: "2026-07-30T19:05:00.000Z",
    author: authors.teo,
    applause: 96,
    commentCount: 8,
    tags: ["economics", "audio"],
  },
  {
    id: "tools-should-leave-a-trail",
    sourceType: "article",
    sourceUrl: "https://en.wikipedia.org/wiki/Hypertext",
    sourceDomain: "wikipedia.org",
    sourceTitle: "Hypertext",
    sourcePublisher: "Wikipedia",
    excerpt: "Hypertext is text displayed on a computer display or other electronic devices with references to other text that the reader can immediately access.",
    commentary: "A link is not merely navigation. It is an explicit claim about relationship. Annotation makes that relationship legible by preserving why the link mattered at the moment it was made.",
    createdAt: "2026-07-29T14:24:00.000Z",
    author: authors.eduardo,
    applause: 211,
    commentCount: 31,
    tags: ["tools for thought", "web"],
  },
];

export const seedComments: Comment[] = [
  {
    id: "comment-1",
    annotationId: "the-value-of-good-questions",
    author: authors.amelie,
    body: "This reads differently when the clip is kept beside the original pause. The source does part of the thinking.",
    createdAt: "2026-07-31T18:11:00.000Z",
  },
  {
    id: "comment-2",
    annotationId: "the-value-of-good-questions",
    author: authors.teo,
    body: "The compounding point is the one I will keep. Curiosity creates options before it creates answers.",
    createdAt: "2026-07-31T18:37:00.000Z",
  },
];
